### ISSUE TITLE
Create Sign Up Screen

### ISSUE THREAD

**Issue by LDomadia** [LDomadia/tech-demo-1-test#2]
**Tasks**
- [ ] add "Sign Up" header
- [ ] add user name text field
- [ ] add email text field
- [ ] add password field
- [ ] add confirm password field
- [ ] add "Sign Up" button

Link to Figma:
