### ISSUE TITLE
Create New User

### ISSUE THREAD

**Issue by LDomadia** [LDomadia/tech-demo-1-test#3]
**Tasks**
- [ ] check valid username
- [ ] check valid email
- [ ] check strong password
- [ ] check check password and confirm password are same
- [ ] display error if it occurs
- [ ] save user to database when "Sign Up" is pressed
- [ ] navigate to Home Screen
